"""Added table User3

Revision ID: 17fa3ddbd643
Revises: d88d19b935c3
Create Date: 2024-09-30 09:52:28.254378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17fa3ddbd643'
down_revision: Union[str, None] = 'd88d19b935c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # Modifikacije tabela koristeći batch_alter_table
    with op.batch_alter_table('admin', schema=None) as batch_op:
        # Kreiraj FOREIGN KEY na 'admin' tabeli povezan sa 'user' tabelom
        batch_op.create_foreign_key('fk_admin_username', 'user', ['username'], ['username'])
        # Izbriši kolonu 'hashed_password'
        batch_op.drop_column('hashed_password')

    with op.batch_alter_table('user_professor', schema=None) as batch_op:
        # Kreiraj FOREIGN KEY na 'user_professor' tabeli povezan sa 'user' tabelom
        batch_op.create_foreign_key('fk_professor_username', 'user', ['username'], ['username'])
        # Izbriši kolonu 'hashed_password'
        batch_op.drop_column('hashed_password')

    with op.batch_alter_table('user_student', schema=None) as batch_op:
        # Kreiraj FOREIGN KEY na 'user_student' tabeli povezan sa 'user' tabelom
        batch_op.create_foreign_key('fk_student_username', 'user', ['username'], ['username'])
        # Izbriši kolonu 'hashed_password'
        batch_op.drop_column('hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # Modifikacije tabela koristeći batch_alter_table za povratak na prethodno stanje
    with op.batch_alter_table('user_student', schema=None) as batch_op:
        # Vraćanje kolone 'hashed_password'
        batch_op.add_column(sa.Column('hashed_password', sa.String(), nullable=False))
        # Brisanje FOREIGN KEY constraint-a
        batch_op.drop_constraint('fk_student_username', type_='foreignkey')

    with op.batch_alter_table('user_professor', schema=None) as batch_op:
        # Vraćanje kolone 'hashed_password'
        batch_op.add_column(sa.Column('hashed_password', sa.String(), nullable=False))
        # Brisanje FOREIGN KEY constraint-a
        batch_op.drop_constraint('fk_professor_username', type_='foreignkey')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        # Vraćanje kolone 'hashed_password'
        batch_op.add_column(sa.Column('hashed_password', sa.String(), nullable=False))
        # Brisanje FOREIGN KEY constraint-a
        batch_op.drop_constraint('fk_admin_username', type_='foreignkey')

    # Brisanje tabele 'user'
    op.drop_table('user')