"""Added model Proffesor

Revision ID: 25c92088dea6
Revises: a9d80c440099
Create Date: 2024-09-20 13:22:46.345907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c92088dea6'
down_revision: Union[str, None] = 'a9d80c440099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("professor",
                    sa.Column('id', sa.Integer, primary_key=True),
                    sa.Column('ime', sa.String),
                    sa.Column('prezime', sa.String),
                    sa.Column('departman', sa.String),)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('professor', sa.Column('professor_id', sa.INTEGER(), nullable=False))
    # op.drop_column('professor', 'id')
    # op.drop_constraint(None, 'course', type_='foreignkey')
    # op.drop_column('course', 'profesor_id')
    # ### end Alembic commands ###
    pass
