"""Added tables UserStudent and UserProfessor

Revision ID: 4287cada927d
Revises: 4acfb3360491
Create Date: 2024-09-26 15:08:42.331781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4287cada927d'
down_revision: Union[str, None] = '4acfb3360491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('user_professor',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('username', sa.String(), nullable=False),
    # sa.Column('hashed_password', sa.String(), nullable=False),
    # sa.Column('professor_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('username')
    # )
    # op.create_table('user_student',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('username', sa.String(), nullable=False),
    # sa.Column('hashed_password', sa.String(), nullable=False),
    # sa.Column('student_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('username')
    # )
    # op.alter_column('course', 'naziv',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('course', 'espb',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'espb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('course', 'naziv',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('user_student')
    op.drop_table('user_professor')
    # ### end Alembic commands ###
