"""Added table Admin

Revision ID: 442e0e856011
Revises: 4287cada927d
Create Date: 2024-09-27 12:01:38.835098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442e0e856011'
down_revision: Union[str, None] = '4287cada927d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('course', 'naziv',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('course', 'espb',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'espb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('course', 'naziv',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
