"""Add table Enrollment

Revision ID: 4acfb3360491
Revises: c528205ef77a
Create Date: 2024-09-23 08:40:44.848107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4acfb3360491'
down_revision: Union[str, None] = 'c528205ef77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('enrollment',
    # sa.Column('student_id', sa.Integer(), nullable=False),
    # sa.Column('sifra_predmeta', sa.String(), nullable=False),
    # sa.Column('datum_upisa', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['sifra_predmeta'], ['course.sifra_predmeta'], name='fk_course_sifra_predmeta'),
    # sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='fk_student_id'),
    # sa.PrimaryKeyConstraint('student_id', 'sifra_predmeta', 'datum_upisa')
    # )
    # op.alter_column('course', 'naziv',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('course', 'espb',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'espb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('course', 'naziv',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('enrollment')
    # ### end Alembic commands ###
