"""Init database

Revision ID: 578c9cd6558d
Revises: 
Create Date: 2024-10-15 09:27:01.641860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578c9cd6558d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STUDENT', 'PROFESSOR', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(), nullable=False),
    sa.Column('prezime', sa.String(), nullable=False),
    sa.Column('departman', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_professor_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(), nullable=False),
    sa.Column('prezime', sa.String(), nullable=False),
    sa.Column('indeks', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_student_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indeks')
    )
    op.create_table('course',
    sa.Column('sifra_predmeta', sa.String(), nullable=False),
    sa.Column('naziv', sa.String(), nullable=False),
    sa.Column('espb', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profesor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('sifra_predmeta')
    )
    op.create_table('enrollment',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('sifra_predmeta', sa.String(), nullable=False),
    sa.Column('datum_upisa', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sifra_predmeta'], ['course.sifra_predmeta'], name='fk_course_sifra_predmeta'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='fk_student_id'),
    sa.PrimaryKeyConstraint('student_id', 'sifra_predmeta', 'datum_upisa')
    )
    op.create_table('exam',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('sifra_predmeta', sa.String(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('ocena', sa.Integer(), nullable=False),
    sa.Column('polozen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sifra_predmeta'], ['course.sifra_predmeta'], name='fk_course_sifra_predmeta'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='fk_student_id'),
    sa.PrimaryKeyConstraint('student_id', 'sifra_predmeta', 'datum')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam')
    op.drop_table('enrollment')
    op.drop_table('course')
    op.drop_table('student')
    op.drop_table('professor')
    op.drop_table('user')
    # ### end Alembic commands ###
