"""Added model Proffesor1

Revision ID: c528205ef77a
Revises: 25c92088dea6
Create Date: 2024-09-20 13:39:17.329505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c528205ef77a'
down_revision: Union[str, None] = '25c92088dea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'new_course',
        sa.Column('sifra_predmeta', sa.String, primary_key=True),
        sa.Column('naziv', sa.String, nullable=True),
        sa.Column('espb', sa.Integer, nullable=True),
        sa.Column('profesor_id', sa.Integer,sa.ForeignKey('professor.id'), nullable=False),  # Set NOT NULL ovde
    )

    # 2. Prebaci podatke iz stare tabele u novu
    op.execute('''
        INSERT INTO new_course (sifra_predmeta, naziv, espb, profesor_id)
        SELECT sifra_predmeta, naziv, espb, profesor_id FROM course;
    ''')

    # 3. Obriši staru tabelu
    op.drop_table('course')

    # 4. Preimenuj novu tabelu u staro ime
    op.rename_table('new_course', 'course')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint('fk_professor_id', 'course', type_='foreignkey')
    #op.alter_column('course', 'profesor_id',
    #           existing_type=sa.INTEGER(),
    #           nullable=True)
    op.drop_table('professor')
    # ### end Alembic commands ###
