"""Added table User2

Revision ID: d88d19b935c3
Revises: 1d2342b15ba1
Create Date: 2024-09-30 09:48:06.282776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88d19b935c3'
down_revision: Union[str, None] = '1d2342b15ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('user',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('username', sa.String(), nullable=False),
    # sa.Column('hashed_password', sa.String(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('username')
    # )
    # op.create_foreign_key(None, 'admin', 'user', ['username'], ['username'])
    # op.drop_column('admin', 'hashed_password')
    # op.create_foreign_key(None, 'user_professor', 'user', ['username'], ['username'])
    # op.drop_column('user_professor', 'hashed_password')
    # op.create_foreign_key(None, 'user_student', 'user', ['username'], ['username'])
    # op.drop_column('user_student', 'hashed_password')
    # ### end Alembic commands ###
    op.drop_table('User')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_student', sa.Column('hashed_password', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'user_student', type_='foreignkey')
    op.add_column('user_professor', sa.Column('hashed_password', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'user_professor', type_='foreignkey')
    op.alter_column('course', 'espb',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('course', 'naziv',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('admin', sa.Column('hashed_password', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_table('user')
    # ### end Alembic commands ###
